[package]
name = "rust-freqdist"
description = "An implementation of a Frequency Distribution in Rust"
version = "0.1.3"
license = "MIT"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]
repository = "https://github.com/ferristseng/rust-freqdist"

[lib]
name = "freqdist"
path = "src/lib.rs"
